#!/bin/bash

# target: ~/.xsessionrc

# xmodmap ~/scripts/speedswapper.xmodmap

xset +fp ~/.fonts/bitocra
xset fp rehash


xrdb -load .Xresources

# redshift &

# xscreensaver
if [ "$XDG_CURRENT_DESKTOP" != "KDE" ];
then 
    xscreensaver -no-splash &
fi
