#!/bin/bash

# target: ~/.xsessionrc

# xmodmap ~/scripts/speedswapper.xmodmap

xset +fp ~/.fonts/bitocra
xset fp rehash


xrdb -load .Xresources

# redshift -l 51.44:7.73 &

# xscreensaver
if [ "$XDG_CURRENT_DESKTOP" != "KDE" ];
then 
    xscreensaver -no-splash &
fi

export WINIT_HIDPI_FACTOR=1
